
package annotation;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MyCompany", targetNamespace = "http://annotation/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyCompany {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMyDepts", targetNamespace = "http://annotation/", className = "annotation.SetMyDepts")
    @ResponseWrapper(localName = "setMyDeptsResponse", targetNamespace = "http://annotation/", className = "annotation.SetMyDeptsResponse")
    public void setMyDepts(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Dept> arg0);

    /**
     * 
     * @return
     *     returns java.util.List<annotation.Dept>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyDepts", targetNamespace = "http://annotation/", className = "annotation.GetMyDepts")
    @ResponseWrapper(localName = "getMyDeptsResponse", targetNamespace = "http://annotation/", className = "annotation.GetMyDeptsResponse")
    public List<Dept> getMyDepts();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployeeToDept", targetNamespace = "http://annotation/", className = "annotation.AddEmployeeToDept")
    @ResponseWrapper(localName = "addEmployeeToDeptResponse", targetNamespace = "http://annotation/", className = "annotation.AddEmployeeToDeptResponse")
    public boolean addEmployeeToDept(
        @WebParam(name = "arg0", targetNamespace = "")
        Emp arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns annotation.Dept
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeptInfo", targetNamespace = "http://annotation/", className = "annotation.GetDeptInfo")
    @ResponseWrapper(localName = "getDeptInfoResponse", targetNamespace = "http://annotation/", className = "annotation.GetDeptInfoResponse")
    public Dept getDeptInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
